### ISSUE TITLE
Routing & Landing Gallery Page

### ISSUE THREAD

**Issue by EmilyHu1224** [cbwestaway/AgentExplorer#1]
URI routing
Landing gallery page with placeholder images & titles for these models:
* Forest Fire
* Conway's Game of Life
* Ising Model
* Schelling's Segregation Model
* Urban Development
* Invasive Plant Species
* Sand Toppling

For all unimplemented page, show a "coming soon" message upon hover

**Comment by cbwestaway** [comment]
Final touches covered by #12 . Closing.
